package dearden.voidspace.entities.components;

public enum ComponentType {

	RENDER, ANIMATION, LIGHTING, PARTICLE,
	SOUND, MOTION, PHYSICS, CONTROL, AI_CONTROL, FOLLOW, 
	CHASSIS, ADDON, WEAPON, SECONDARY_WEP, ARMOR, THRUST, HEALTH, DAMAGE, SHEILD,
	DESTRUCTABLE, REFLECTABLE, EXPLOSION, HEAT, HEAT_SEEKING;
	
}
